name: "Generate License Report"
description: "Runs the license generation script"
runs:
  using: "composite"
  steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        # Ensure we check out this repository, and not the repository
        # of the downstream GitHub Actions workflow that is importing
        # our action.
        repository: element-hq/reproduce-rust-licenses
        path: reproduce-rust-licenses
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Run script
      shell: bash
      run: python generate-licenses.py --licenses "${{ inputs.licenses }}"
inputs:
  licenses:
    description: "Comma-separated list of licenses"
    required: true
